# Generated by Django 6.1 on 2026-09-04 15:28

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDepartment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Warehouse & Fulfilment', 'Customer Support'.", max_length=100, unique=True, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this department does.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive departments are hidden from the staff profile form but existing assignments are preserved.', verbose_name='Active')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Controls order in dropdowns. Lower = first.', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Staff Department',
                'verbose_name_plural': 'Staff Departments',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('role', models.CharField(blank=True, help_text="Coarse role label. Use Django Groups/Permissions for fine-grained access control. This field is for display and broad categorization only (e.g. 'Warehouse Manager', 'Customer Support Agent'). Staff permissions are controlled via auth.Group assignments.", max_length=100, verbose_name='Role / Job Title')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/staff/', verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to revoke staff access without deleting the account. Both this flag AND UserAccount.is_active must be True for access.', verbose_name='Staff Active')),
                ('notes', models.TextField(blank=True, help_text='Private admin-only notes. Not visible to the staff member.', verbose_name='Internal Notes')),
                ('department', models.ForeignKey(blank=True, help_text='Operational area. Manage departments in Staff - Departments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staff.staffdepartment', verbose_name='Department')),
                ('user', models.OneToOneField(help_text='The linked UserAccount must have is_staff=True.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
