# Generated by Django 6.1 on 2026-09-04 15:28

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfilment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Allocation'), ('ALLOCATED', 'Allocated'), ('PICKED', 'Picked'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10, verbose_name='Status')),
                ('fulfilment_type', models.CharField(choices=[('shipment', 'Shipment'), ('local_delivery', 'Local Delivery'), ('store_pickup', 'Store Pickup'), ('download', 'Download'), ('email', 'Email Delivery'), ('license_key', 'License Key'), ('streaming', 'Streaming Access'), ('account_provision', 'Account Provisioning'), ('subscription', 'Recurring Subscription'), ('service_appointment', 'Service Appointment'), ('event_access', 'Event Access'), ('manual', 'Manual Fulfilment')], db_index=True, help_text='Copied from Product.fulfilment_type at order placement. Determines which handler the routing registry dispatches to.', max_length=25, verbose_name='Fulfilment Type')),
                ('tracking_number', models.CharField(blank=True, max_length=255, verbose_name='Tracking Number')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Carrier')),
                ('dispatch_error', models.TextField(blank=True, verbose_name='Dispatch Error')),
                ('allocated_at', models.DateTimeField(blank=True, null=True, verbose_name='Allocated At')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='Picked At')),
                ('packed_at', models.DateTimeField(blank=True, null=True, verbose_name='Packed At')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Shipped At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfilment', to='orders.orderitem', verbose_name='Order Item')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Null for non-physical fulfilment types.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilments', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Fulfilment',
                'verbose_name_plural': 'Fulfilments',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FulfilmentStatusHistory',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, choices=[('PENDING', 'Pending Allocation'), ('ALLOCATED', 'Allocated'), ('PICKED', 'Picked'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], help_text='Empty for the initial PENDING row.', max_length=10, verbose_name='Previous Status')),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending Allocation'), ('ALLOCATED', 'Allocated'), ('PICKED', 'Picked'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=10, verbose_name='New Status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Null for system-triggered transitions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilment_status_changes', to='staff.staffprofile', verbose_name='Changed By')),
                ('fulfilment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delivery.fulfilment', verbose_name='Fulfilment')),
            ],
            options={
                'verbose_name': 'Fulfilment Status History',
                'verbose_name_plural': 'Fulfilment Status Histories',
                'ordering': ['changed_at'],
            },
        ),
    ]
