# Generated by Django 6.1 on 2026-08-26 05:08

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_initial'),
        ('customers', '0001_initial'),
        ('pricing', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, help_text='Human-readable reference generated at placement, e.g. ORD-00001234.', max_length=30, unique=True, verbose_name='Order Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned')], db_index=True, default='PENDING', max_length=20, verbose_name='Order Status')),
                ('shipping_address', models.JSONField(help_text='Snapshot of the delivery address at checkout time. Keys: full_name, contact_number, address_line1, address_line2, landmark, city, state, country, pincode.', verbose_name='Shipping Address')),
                ('billing_address', models.JSONField(help_text='Snapshot of the billing address. Same structure as shipping_address.', verbose_name='Billing Address')),
                ('sub_total', models.DecimalField(decimal_places=2, help_text='Sum of line totals before discounts, shipping, and tax.', max_digits=12, verbose_name='Sub-total')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping Cost')),
                ('shipping_method', models.CharField(blank=True, help_text="Snapshot of the shipping method name chosen at checkout, e.g. 'Standard Post'. Blank when the order has no carrier-bound items (e.g. store pickup only).", max_length=100, verbose_name='Shipping Method')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='sub_total - discount_amount + shipping_cost + tax_amount.', max_digits=12, verbose_name='Total Amount')),
                ('coupon_code', models.CharField(blank=True, help_text='Denormalised for display. Full audit in promotion.CouponRedemption.', max_length=50, verbose_name='Coupon Code Used')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('REQUIRES_ACTION', 'Requires Action'), ('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], db_index=True, default='UNPAID', max_length=20, verbose_name='Payment Status')),
                ('notes', models.TextField(blank=True, verbose_name='Customer / Staff Notes')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='pricing.currency', verbose_name='Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customerprofile', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_sku', models.CharField(max_length=100, verbose_name='SKU (snapshot)')),
                ('variant_name', models.CharField(max_length=255, verbose_name='Product Name (snapshot)')),
                ('variant_attributes', models.JSONField(default=dict, help_text="Dict of label-value pairs at order time, e.g. {'Colour': 'Red', 'Size': 'M'}.", verbose_name='Variant Attributes (snapshot)')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Pre-tax price per unit at purchase time.', max_digits=12, verbose_name='Unit Price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage applied at purchase time.', max_digits=5, verbose_name='Tax Rate (%)')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='unit_price x quantity (pre-tax).', max_digits=12, verbose_name='Line Total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
                ('variant', models.ForeignKey(blank=True, help_text='Live reference for reporting. Null if variant is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalogue.productvariant', verbose_name='Product Variant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['order', 'variant_sku'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('old_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned')], help_text='Empty for the very first status entry.', max_length=20, verbose_name='Previous Status')),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned')], max_length=20, verbose_name='New Status')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Null when the transition is triggered by an automated process.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to='staff.staffprofile', verbose_name='Changed By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Item Arrived Damaged'), ('WRONG_ITEM', 'Wrong Item Received'), ('NOT_AS_DESCRIBED', 'Not as Described'), ('CHANGED_MIND', 'Changed My Mind'), ('DEFECTIVE', 'Item is Defective / Not Working'), ('MISSING_PARTS', 'Missing Parts or Accessories'), ('OTHER', 'Other')], db_index=True, default='OTHER', help_text='Top-level reason provided by the customer. Staff can record a more detailed internal reason on the linked Refund.', max_length=20, verbose_name='Return Reason')),
                ('customer_note', models.TextField(blank=True, help_text='Free-text explanation provided by the customer at request time.', verbose_name='Customer Note')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURN_SHIPPED', 'Return Shipped by Customer'), ('RECEIVED', 'Items Received at Warehouse'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled by Customer')], db_index=True, default='PENDING', help_text='Do not update directly. Use ReturnRequestService which also writes a status history row.', max_length=15, verbose_name='Status')),
                ('staff_note', models.TextField(blank=True, help_text='Internal note added by staff during review. Not shown to the customer.', verbose_name='Staff Note')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('received_at', models.DateTimeField(blank=True, help_text='Set when the warehouse confirms all items have been received.', null=True, verbose_name='Items Received At')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set when the return is fully resolved and refund issued.', null=True, verbose_name='Completed At')),
                ('order', models.ForeignKey(help_text='The order this return request is for. Must be in DELIVERED or RETURN_REQUESTED status when created.', on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.order', verbose_name='Order')),
                ('requested_by', models.ForeignKey(help_text='Customer who submitted this return request.', on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='customers.customerprofile', verbose_name='Requested By')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff member who approved or rejected this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_return_requests', to='staff.staffprofile', verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_requested', models.PositiveSmallIntegerField(help_text='Number of units the customer wants to return. Must be ≥ 1 and ≤ the original OrderItem.quantity.', verbose_name='Quantity Requested')),
                ('quantity_received', models.PositiveSmallIntegerField(default=0, help_text='Units actually received and accepted at the warehouse after inspection. Set by ReturnRequestService.receive(). May differ from quantity_requested if some items were missing or not accepted.', verbose_name='Quantity Received')),
                ('condition_note', models.TextField(blank=True, help_text="Warehouse staff note on item condition after inspection, e.g. 'missing original packaging', 'item not defective - rejected'.", verbose_name='Condition Note')),
                ('order_item', models.ForeignKey(help_text='The specific order line being returned. Must belong to the same order as the parent ReturnRequest.', on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem', verbose_name='Order Item')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.returnrequest', verbose_name='Return Request')),
            ],
            options={
                'verbose_name': 'Return Request Item',
                'verbose_name_plural': 'Return Request Items',
                'ordering': ['return_request', 'order_item__variant_sku'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('old_status', models.CharField(blank=True, choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURN_SHIPPED', 'Return Shipped by Customer'), ('RECEIVED', 'Items Received at Warehouse'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled by Customer')], help_text='Empty for the initial (PENDING) entry.', max_length=15, verbose_name='Previous Status')),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURN_SHIPPED', 'Return Shipped by Customer'), ('RECEIVED', 'Items Received at Warehouse'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled by Customer')], max_length=15, verbose_name='New Status')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Null when triggered by an automated process.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_status_changes', to='staff.staffprofile', verbose_name='Changed By')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.returnrequest', verbose_name='Return Request')),
            ],
            options={
                'verbose_name': 'Return Request Status History',
                'verbose_name_plural': 'Return Request Status Histories',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnShipment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, db_index=True, help_text='Carrier tracking reference provided by the customer. Set when status transitions to RETURN_SHIPPED.', max_length=100, verbose_name='Tracking Number')),
                ('carrier', models.CharField(blank=True, help_text="Carrier name entered by the customer, e.g. 'FedEx', 'DHL', 'Royal Mail'.", max_length=100, verbose_name='Carrier')),
                ('shipped_at', models.DateTimeField(blank=True, help_text='When the customer marked the parcel as dispatched.', null=True, verbose_name='Shipped At')),
                ('expected_at', models.DateTimeField(blank=True, help_text='Estimated arrival date at the warehouse.', null=True, verbose_name='Expected At')),
                ('received_at', models.DateTimeField(blank=True, help_text='When warehouse staff confirmed receipt. Set by ReturnRequestService.receive().', null=True, verbose_name='Received At')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the shipment, e.g. packaging condition, partial receipt details.', verbose_name='Notes')),
                ('received_by', models.ForeignKey(blank=True, help_text='Warehouse staff member who processed the incoming parcel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_return_shipments', to='staff.staffprofile', verbose_name='Received By')),
                ('return_request', models.OneToOneField(help_text='The return request this shipment fulfils. Create only after the request is APPROVED.', on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.returnrequest', verbose_name='Return Request')),
            ],
            options={
                'verbose_name': 'Return Shipment',
                'verbose_name_plural': 'Return Shipments',
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('sub_total__gte', 0)), name='order_sub_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='order_discount_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_cost__gte', 0)), name='order_shipping_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='order_tax_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='order_total_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('sub_total'), '-', models.F('discount_amount')), '+', models.F('shipping_cost')), '+', models.F('tax_amount')))), name='order_total_amount_formula'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='order_item_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0)), name='order_item_tax_rate_non_negative'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', 'status'], name='orders_retu_order_i_62acda_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', '-created'], name='orders_retu_status_9ae809_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnrequestitem',
            constraint=models.UniqueConstraint(fields=('return_request', 'order_item'), name='unique_return_item_per_request'),
        ),
        migrations.AddConstraint(
            model_name='returnrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_requested__gte', 1)), name='return_item_quantity_requested_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='returnrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='return_item_quantity_received_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='returnrequestitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__lte', models.F('quantity_requested'))), name='return_item_received_lte_requested'),
        ),
    ]
