# Generated by Django 6.1 on 2026-08-23 05:23

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipping_method', models.CharField(blank=True, help_text="Name of the shipping method selected, e.g. 'Standard Post'.", max_length=100, verbose_name='Shipping Method')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Quoted cost for the selected shipping method.', max_digits=12, verbose_name='Shipping Cost')),
                ('coupon_code', models.CharField(blank=True, help_text='Code applied by the customer. Validated in the checkout service.', max_length=50, verbose_name='Coupon Code')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROCESSING', 'Processing Payment'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned'), ('FAILED', 'Failed')], db_index=True, default='ACTIVE', max_length=12, verbose_name='Status')),
                ('step', models.CharField(choices=[('ADDRESS', 'Address'), ('SHIPPING', 'Shipping Method'), ('PAYMENT', 'Payment'), ('CONFIRMATION', 'Confirmation')], default='ADDRESS', max_length=12, verbose_name='Current Step')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this session should be considered stale. Set to e.g. now + 24 hours when the session is created.', null=True, verbose_name='Expires At')),
                ('billing_address', models.ForeignKey(blank=True, help_text='Selected billing address. Snapshotted into Order.billing_address (JSON) at order creation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_checkout_sessions', to='customers.customeraddress', verbose_name='Billing Address')),
            ],
            options={
                'verbose_name': 'Checkout Session',
                'verbose_name_plural': 'Checkout Sessions',
                'ordering': ['-created'],
            },
        ),
    ]
