# Generated by Django 6.1 on 2026-08-23 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('pricing', '0001_initial'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='cart',
            field=models.OneToOneField(help_text='The cart this checkout is processing.', on_delete=django.db.models.deletion.PROTECT, related_name='checkout_session', to='shopping.cart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to='pricing.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Null for guest checkouts. Identified by cart.session_key.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='customers.customerprofile', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='order',
            field=models.OneToOneField(blank=True, help_text='Set after the payment is confirmed and the Order is created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_session', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text="Selected shipping address. At order creation this is snapshotted into Order.shipping_address (JSON) so later edits don't affect the order.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_checkout_sessions', to='customers.customeraddress', verbose_name='Shipping Address'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_cost__gte', 0)), name='checkout_session_shipping_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('order__isnull', False), _connector='OR'), name='checkout_completed_requires_order'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('step', 'ADDRESS'), _negated=True), ('shipping_address__isnull', False), _connector='OR'), name='checkout_address_step_requires_address'),
        ),
        migrations.AddConstraint(
            model_name='checkoutsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('step', 'PAYMENT'), _negated=True), ('billing_address__isnull', False), _connector='OR'), name='checkout_payment_step_requires_billing'),
        ),
    ]
