# Generated by Django 6.1 on 2026-09-04 15:28

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Tax Class',
                'verbose_name_plural': 'Tax Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='ISO 4217 three-letter currency code, e.g. USD.', max_length=3, unique=True, verbose_name='Code')),
                ('symbol', models.CharField(help_text='Display symbol unicode used in prices, e.g. $ or £.', max_length=10, verbose_name='Symbol unicode')),
                ('name', models.CharField(help_text="Full English name, e.g. 'US Dollar'.", max_length=50, verbose_name='Name')),
                ('is_default', models.BooleanField(default=False, help_text="The storefront's primary currency. Only one currency should be set as default.", verbose_name='Default Currency')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active currencies are offered at checkout and used for pricing. Deactivate instead of deleting to preserve historical payment records.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['-is_default', '-is_active', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_currency')],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_type', models.CharField(choices=[('BASE', 'Base Price'), ('SALE', 'Sale Price')], default='BASE', max_length=4, verbose_name='Price Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Pre-tax price in the given currency.', max_digits=12, verbose_name='Amount')),
                ('valid_from', models.DateTimeField(blank=True, help_text='When this price becomes active. Null = active immediately. Used for SALE prices.', null=True, verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(blank=True, help_text='When this price expires. Null = no expiry. Used for SALE prices.', null=True, verbose_name='Valid To')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='pricing.currency', verbose_name='Currency')),
                ('variant', models.ForeignKey(help_text='The variant being priced. Tax class is resolved via: variant - product - tax_class.', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalogue.productvariant', verbose_name='Product Variant')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricing',
                'ordering': ['variant', 'currency', 'price_type'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('price_type', 'BASE')), fields=('variant', 'currency', 'price_type'), name='unique_price_per_variant_currency_type_base_only'), models.UniqueConstraint(condition=models.Q(('price_type', 'SALE')), fields=('variant', 'currency', 'price_type', 'valid_from'), name='unique_price_per_variant_currency_type_sale_with_date'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='pricing_amount_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', django_countries.fields.CountryField(help_text="ISO 3166-1 alpha-2 country code, e.g. 'GB', 'US', 'IN'.", max_length=2, verbose_name='Country')),
                ('state', models.CharField(blank=True, help_text='Optional. ISO 3166-2 subdivision or free-text state name. Leave blank for a country-wide rate.', max_length=100, verbose_name='State / Province')),
                ('rate_percent', models.DecimalField(decimal_places=2, help_text='Tax percentage, e.g. 20.00 for 20%, 5.00 for 5%.', max_digits=5, verbose_name='Rate (%)')),
                ('effective_from', models.DateField(help_text='Date this rate becomes applicable.Set this deliberately -- not auto-filled.', verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, help_text='Date this rate expires. Leave blank if the rate has no planned end.', null=True, verbose_name='Effective To')),
                ('tax_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='pricing.taxclass', verbose_name='Tax Class')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['country', 'state', 'tax_class', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('tax_class', 'country', 'state', 'effective_from'), name='unique_tax_rate_per_jurisdiction_date'), models.CheckConstraint(condition=models.Q(('rate_percent__gte', 0)), name='tax_rate_percent_non_negative')],
            },
        ),
    ]
