# Generated by Django 6.1 on 2026-08-18 17:36

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='E.164 format, e.g. +14155552671.', max_length=128, region=None, verbose_name='Phone Number')),
                ('date_of_birth', models.DateField(blank=True, help_text='Used for age-gated products and birthday promotions.', null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer Not to Say')], default='N', max_length=1, verbose_name='Gender')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/customers/', verbose_name='Avatar')),
                ('accepts_marketing', models.BooleanField(default=False, help_text='Customer opted in to promotional emails and notifications.', verbose_name='Accepts Marketing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('landmark', models.CharField(blank=True, max_length=100, verbose_name='Landmark')),
                ('city', models.CharField(max_length=100, verbose_name='City / District')),
                ('state', models.CharField(max_length=100, verbose_name='State / Province')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('pincode', models.CharField(max_length=20, verbose_name='Pin / Zip Code')),
                ('address_type', models.CharField(choices=[('SHIP', 'Shipping'), ('BILL', 'Billing'), ('BOTH', 'Both')], default='BOTH', max_length=4, verbose_name='Address Type')),
                ('full_name', models.CharField(help_text='Name printed on the shipping label.', max_length=150, verbose_name='Recipient Full Name')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number for the delivery courier.', max_length=128, region=None, verbose_name='Contact Number')),
                ('is_default', models.BooleanField(default=False, help_text='Preferred address for this type. Only one default is allowed per address_type per user.', verbose_name='Default Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customerprofile', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['-is_default', '-created'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('customer', 'address_type'), name='unique_default_address_per_customer_type')],
            },
        ),
    ]
