[mypy]
python_version = 3.14
ignore_missing_imports = True
check_untyped_defs = True
warn_redundant_casts = True
warn_unused_ignores = True
strict = True
plugins = mypy_django_plugin.main

[mypy-*.migrations.*]
ignore_errors = True


[mypy.plugins.django-stubs]
django_settings_module = config.settings.test
