[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test

addopts =
    --import-mode=importlib
    -x

minversion = 9.0

python_files =
    tests.py
    test_*.py

python_classes =
    Test*

python_functions =
    test_*
