# Generated by Django 6.1 on 2026-08-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_publish_reviews', models.BooleanField(default=False, help_text='When True, newly submitted reviews are immediately visible on the storefront (is_published=True) without staff approval. When False, staff must publish each review manually.', verbose_name='Auto-publish Reviews')),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
