# Generated by Django 6.1 on 2026-08-26 05:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('customers', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Django session key for guest cart identification.', max_length=40, verbose_name='Session Key')),
                ('cart_type', models.CharField(choices=[('ACTIVE', 'Active Cart'), ('SAVED', 'Saved for Later'), ('BUY_NOW', 'Buy Now'), ('MERGED', 'Merged (guest cart archived after login)')], default='ACTIVE', max_length=10, verbose_name='Cart Type')),
                ('coupon_code', models.CharField(blank=True, help_text='Coupon applied to this cart. Validated at checkout.', max_length=50, verbose_name='Coupon Code')),
                ('currency', models.ForeignKey(blank=True, help_text='Currency used to display prices in this cart.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='pricing.currency', verbose_name='Currency')),
                ('customer', models.ForeignKey(blank=True, help_text='Null for guest carts. Identified by session_key instead.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='customers.customerprofile', verbose_name='Customer')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Set by CartMergeService when this guest cart is merged into a customer cart. The referenced cart is the surviving cart. Only populated when cart_type = MERGED.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_carts', to='shopping.cart', verbose_name='Merged Into')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_price_at_add', models.DecimalField(blank=True, decimal_places=2, help_text='Base price per unit when this item was added. Used to detect price changes before checkout.', max_digits=12, null=True, verbose_name='Unit Price at Add')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.cart', verbose_name='Cart')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalogue.productvariant', verbose_name='Product Variant')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_public', models.BooleanField(default=False, help_text='Allow anyone with the link to view this collection.', verbose_name='Public')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='customers.customerprofile', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.collection', verbose_name='Collection')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='catalogue.productvariant', verbose_name='Product Variant')),
            ],
            options={
                'verbose_name': 'Collection Item',
                'verbose_name_plural': 'Collection Items',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='customers.customerprofile', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='catalogue.productvariant', verbose_name='Product Variant')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.wishlist', verbose_name='Wishlist')),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', False)), fields=('customer', 'cart_type'), name='unique_cart_type_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('session_key', 'cart_type'), name='unique_cart_type_per_session'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'variant'), name='unique_variant_per_cart'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'variant'), name='unique_variant_per_collection'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('wishlist', 'variant'), name='unique_variant_per_wishlist'),
        ),
    ]
