# Generated by Django 6.1 on 2026-08-26 05:08

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=False, help_text='Must also be within start/end date range to be live.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount'), ('FREE_SHIPPING', 'Free Shipping')], default='PERCENTAGE', max_length=15, verbose_name='Discount Type')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (0-100) for PERCENTAGE type, or a fixed currency amount for FIXED type. Leave blank for FREE_SHIPPING.', max_digits=12, null=True, verbose_name='Discount Value')),
                ('applies_to', models.CharField(choices=[('CART', 'Entire Cart'), ('PRODUCT', 'Specific Product'), ('CATEGORY', 'Product Category'), ('VARIANT', 'Specific Variant')], default='CART', max_length=10, verbose_name='Applies To')),
                ('minimum_cart_value', models.DecimalField(decimal_places=2, default=0, help_text='Cart sub-total must reach this before the discount applies. 0 = no minimum.', max_digits=12, verbose_name='Minimum Cart Value')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Caps the discount value. Useful for percentage discounts. Null = no cap.', max_digits=12, null=True, verbose_name='Maximum Discount Amount')),
                ('usage_limit_total', models.PositiveIntegerField(blank=True, help_text='Maximum total redemptions. Null = unlimited.', null=True, verbose_name='Total Usage Limit')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times this discount has been redeemed.', verbose_name='Times Used')),
                ('slug', models.SlugField(help_text="URL-safe unique identifier for this discount rule, e.g. 'back-to-school-cart-10pct'. Auto-generated from campaign and discount type if left blank.", max_length=100, unique=True, verbose_name='Slug')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='promotions.campaign', verbose_name='Campaign')),
                ('target_category', models.ForeignKey(blank=True, help_text='Set when applies_to = CATEGORY.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='catalogue.productcategory', verbose_name='Target Category')),
                ('target_product', models.ForeignKey(blank=True, help_text='Set when applies_to = PRODUCT.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='catalogue.product', verbose_name='Target Product')),
                ('target_variant', models.ForeignKey(blank=True, help_text='Set when applies_to = VARIANT.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='catalogue.productvariant', verbose_name='Target Variant')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Code customers enter at checkout. Stored and compared case-insensitively in the service layer.', max_length=50, unique=True, verbose_name='Coupon Code')),
                ('usage_limit_total', models.PositiveIntegerField(blank=True, help_text='Maximum total redemptions. Null = unlimited.', null=True, verbose_name='Total Usage Limit')),
                ('usage_limit_per_user', models.PositiveSmallIntegerField(default=1, help_text='How many times a single user may use this code.', verbose_name='Per-User Usage Limit')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid To')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='promotions.discount', verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Redeemed At')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.coupon', verbose_name='Coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='customers.customerprofile', verbose_name='Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Coupon Redemption',
                'verbose_name_plural': 'Coupon Redemptions',
                'ordering': ['-redeemed_at'],
                'constraints': [models.UniqueConstraint(fields=('coupon', 'order'), name='unique_coupon_per_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applies_to', 'CART'), ('target_product__isnull', True), ('target_category__isnull', True), ('target_variant__isnull', True)), ('applies_to', 'PRODUCT'), ('applies_to', 'CATEGORY'), ('applies_to', 'VARIANT'), _connector='OR'), name='discount_cart_has_no_target'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applies_to', 'PRODUCT'), ('target_product__isnull', False), ('target_category__isnull', True), ('target_variant__isnull', True)), models.Q(('applies_to', 'PRODUCT'), _negated=True), _connector='OR'), name='discount_product_target_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applies_to', 'CATEGORY'), ('target_product__isnull', True), ('target_category__isnull', False), ('target_variant__isnull', True)), models.Q(('applies_to', 'CATEGORY'), _negated=True), _connector='OR'), name='discount_category_target_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applies_to', 'VARIANT'), ('target_product__isnull', True), ('target_category__isnull', True), ('target_variant__isnull', False)), models.Q(('applies_to', 'VARIANT'), _negated=True), _connector='OR'), name='discount_variant_target_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_cart_value__gte', 0)), name='discount_minimum_cart_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(('max_discount_amount__isnull', True), ('max_discount_amount__gt', 0), _connector='OR'), name='discount_max_discount_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'FIXED'), _negated=True), ('value__isnull', True), ('value__gt', 0), _connector='OR'), name='discount_fixed_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'PERCENTAGE'), _negated=True), ('value__isnull', True), models.Q(('value__gt', 0), ('value__lte', 100)), _connector='OR'), name='discount_percentage_value_range'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'FREE_SHIPPING'), _negated=True), ('value__isnull', True), _connector='OR'), name='discount_free_shipping_value_null'),
        ),
    ]
