# Generated by Django 6.1 on 2026-08-26 05:08

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('pricing', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name shown to customers, e.g. 'Credit / Debit Card'.", max_length=100, unique=True, verbose_name='Name')),
                ('gateway_code', models.CharField(blank=True, help_text="Machine code passed to the payment gateway adapter, e.g. 'card', 'upi'. Leave blank for offline methods.", max_length=50, verbose_name='Gateway Code')),
                ('description', models.TextField(blank=True, help_text='Optional detail shown to the customer at checkout.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive methods are hidden from checkout but historical payment records keep their method.', verbose_name='Active')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Controls order in the checkout payment step. Lower = first.', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RefundReason',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Item Damaged / Defective', 'Customer Changed Mind'.", max_length=150, unique=True, verbose_name='Reason')),
                ('description', models.TextField(blank=True, help_text='Optional internal notes about when to use this reason.', verbose_name='Description')),
                ('requires_return', models.BooleanField(default=False, help_text='If True, the refund workflow will prompt staff to confirm the item has been returned before issuing the refund.', verbose_name='Requires Item Return')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive reasons are hidden from new refund forms but existing refunds keep their reason.', verbose_name='Active')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Controls order in the refund form. Lower = first.', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Refund Reason',
                'verbose_name_plural': 'Refund Reasons',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(help_text="Provider identifier, e.g. 'stripe', 'paypal', 'razorpay'.", max_length=50, verbose_name='Payment Gateway')),
                ('transaction_id', models.CharField(db_index=True, help_text="Provider's unique transaction reference.", max_length=255, unique=True, verbose_name='Transaction ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('REQUIRES_ACTION', 'Requires Action'), ('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], db_index=True, default='PENDING', help_text='Do not edit directly. Use the payment service which also writes a PaymentStatusHistory row.', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount charged, inclusive of tax.', max_digits=12, verbose_name='Amount')),
                ('raw_response', models.JSONField(default=dict, help_text='Full JSON payload from the gateway. Never expose to customers.', verbose_name='Raw Gateway Response')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='Initiated At')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set by the payment service when a terminal status is reached.', null=True, verbose_name='Completed At')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pricing.currency', verbose_name='Currency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Order')),
                ('payment_method', models.ForeignKey(blank=True, help_text='How the customer paid. Manage available methods in Payment - Payment Methods.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('REQUIRES_ACTION', 'Requires Action'), ('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], help_text='Empty for the initial status entry.', max_length=20, verbose_name='Previous Status')),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('REQUIRES_ACTION', 'Requires Action'), ('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], max_length=20, verbose_name='New Status')),
                ('gateway_event', models.CharField(blank=True, help_text="The gateway webhook event that triggered this transition, e.g. 'payment_intent.succeeded', 'charge.failed'.", max_length=100, verbose_name='Gateway Event')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Null when triggered by an automated gateway callback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_status_changes', to='staff.staffprofile', verbose_name='Changed By')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='payments.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Payment Status History',
                'verbose_name_plural': 'Payment Status Histories',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text="Provider's refund reference, if issued.", max_length=255, verbose_name='Refund Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Refund Amount')),
                ('notes', models.TextField(blank=True, help_text='Additional detail about why this refund was issued.', verbose_name='Notes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12, verbose_name='Status')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='Payment')),
                ('refunded_by', models.ForeignKey(blank=True, help_text='Staff user who triggered the refund. Null if automated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_refunds', to='staff.staffprofile', verbose_name='Refunded By')),
                ('reason', models.ForeignKey(blank=True, help_text='Why this refund was issued. Manage reasons in Payment - Refund Reasons.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.refundreason', verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(help_text='Number of units refunded in this line item.', verbose_name='Quantity')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount for this line item.', max_digits=12, verbose_name='Amount')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_items', to='orders.orderitem', verbose_name='Order Item')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.refund', verbose_name='Refund')),
            ],
            options={
                'verbose_name': 'Refund Item',
                'verbose_name_plural': 'Refund Items',
                'ordering': ['refund', 'order_item'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='refunditem',
            constraint=models.UniqueConstraint(fields=('refund', 'order_item'), name='unique_refund_item_per_refund_order_item'),
        ),
        migrations.AddConstraint(
            model_name='refunditem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='refund_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='refunditem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_item_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
    ]
