# Generated by Django 6.1 on 2026-08-23 05:23

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Stock Receipt'), ('SALE', 'Sale / Dispatch'), ('RETURN', 'Customer Return'), ('ADJ_IN', 'Adjustment (Increase)'), ('ADJ_OUT', 'Adjustment (Decrease)'), ('XFER_IN', 'Transfer In'), ('XFER_OUT', 'Transfer Out'), ('RESERVE', 'Reserve for Order'), ('RELEASE', 'Release Reservation')], db_index=True, max_length=10, verbose_name='Movement Type')),
                ('delta', models.PositiveIntegerField(help_text='Number of units involved. Always positive -- movement_type determines whether stock increases or decreases.', verbose_name='Units')),
                ('quantity_after', models.IntegerField(default=0, verbose_name='Quantity After')),
                ('reserved_after', models.IntegerField(default=0, verbose_name='Reserved After')),
                ('reference', models.CharField(blank=True, db_index=True, help_text='External reference for this movement. e.g. PO number for receipts, transfer ID for transfers, RMA number for returns.', max_length=100, verbose_name='Reference')),
                ('note', models.TextField(blank=True, help_text='Reason for this movement. Required for ADJUSTMENT_IN and ADJUSTMENT_OUT movements.', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('landmark', models.CharField(blank=True, max_length=100, verbose_name='Landmark')),
                ('city', models.CharField(max_length=100, verbose_name='City / District')),
                ('state', models.CharField(max_length=100, verbose_name='State / Province')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('pincode', models.CharField(max_length=20, verbose_name='Pin / Zip Code')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code', models.CharField(help_text="Short unique identifier used in references, e.g. 'LON-01'.", max_length=20, unique=True, verbose_name='Warehouse Code')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Priority for stock allocation across multiple warehouses. Higher numbers are preferred. Default 0.', verbose_name='Priority')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Contact Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, help_text='Total physical units at this warehouse. Updated automatically by StockMovementService -- do not edit directly.', verbose_name='Quantity on Hand')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Units committed to placed but unfulfilled orders. Updated automatically by StockMovementService -- do not edit directly.', verbose_name='Reserved Quantity')),
                ('reorder_point', models.PositiveIntegerField(blank=True, help_text='Low-stock alert threshold. When available quantity falls below this, alert staff to reorder. Null = no threshold.', null=True, verbose_name='Reorder Point')),
                ('minimum_order_qty', models.PositiveSmallIntegerField(default=1, help_text='Minimum units a customer must purchase per order.', verbose_name='Minimum Order Quantity')),
                ('maximum_order_qty', models.PositiveSmallIntegerField(default=0, help_text='Maximum units per order. 0 = no limit.', verbose_name='Maximum Order Quantity')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalogue.productvariant', verbose_name='Product Variant')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
    ]
