# Generated by Django 6.1 on 2026-08-26 05:08

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_initial'),
        ('orders', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('landmark', models.CharField(blank=True, max_length=100, verbose_name='Landmark')),
                ('city', models.CharField(max_length=100, verbose_name='City / District')),
                ('state', models.CharField(max_length=100, verbose_name='State / Province')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('pincode', models.CharField(max_length=20, verbose_name='Pin / Zip Code')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code', models.CharField(help_text="Short unique identifier used in references, e.g. 'LON-01'.", max_length=20, unique=True, verbose_name='Warehouse Code')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Priority for stock allocation across multiple warehouses. Higher numbers are preferred. Default 0.', verbose_name='Priority')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Contact Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('contact_person', models.ForeignKey(blank=True, help_text='Staff member responsible for this warehouse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to='staff.staffprofile', verbose_name='Contact Person')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, help_text='Total physical units at this warehouse. Updated automatically by StockMovementService -- do not edit directly.', verbose_name='Quantity on Hand')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Units committed to placed but unfulfilled orders. Updated automatically by StockMovementService -- do not edit directly.', verbose_name='Reserved Quantity')),
                ('reorder_point', models.PositiveIntegerField(blank=True, help_text='Low-stock alert threshold. When available quantity falls below this, alert staff to reorder. Null = no threshold.', null=True, verbose_name='Reorder Point')),
                ('minimum_order_qty', models.PositiveSmallIntegerField(default=1, help_text='Minimum units a customer must purchase per order.', verbose_name='Minimum Order Quantity')),
                ('maximum_order_qty', models.PositiveSmallIntegerField(default=0, help_text='Maximum units per order. 0 = no limit.', verbose_name='Maximum Order Quantity')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalogue.productvariant', verbose_name='Product Variant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Stock Receipt'), ('SALE', 'Sale / Dispatch'), ('RETURN', 'Customer Return'), ('ADJ_IN', 'Adjustment (Increase)'), ('ADJ_OUT', 'Adjustment (Decrease)'), ('XFER_IN', 'Transfer In'), ('XFER_OUT', 'Transfer Out'), ('RESERVE', 'Reserve for Order'), ('RELEASE', 'Release Reservation')], db_index=True, max_length=10, verbose_name='Movement Type')),
                ('delta', models.PositiveIntegerField(help_text='Number of units involved. Always positive -- movement_type determines whether stock increases or decreases.', verbose_name='Units')),
                ('quantity_after', models.IntegerField(default=0, verbose_name='Quantity After')),
                ('reserved_after', models.IntegerField(default=0, verbose_name='Reserved After')),
                ('reference', models.CharField(blank=True, db_index=True, help_text='External reference for this movement. e.g. PO number for receipts, transfer ID for transfers, RMA number for returns.', max_length=100, verbose_name='Reference')),
                ('note', models.TextField(blank=True, help_text='Reason for this movement. Required for ADJUSTMENT_IN and ADJUSTMENT_OUT movements.', verbose_name='Note')),
                ('order_item', models.ForeignKey(blank=True, help_text='Set for SALE, RESERVE, and RELEASE movements.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.orderitem', verbose_name='Order Item')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Staff user who triggered this movement. Null = automated/system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='staff.staffprofile', verbose_name='Performed By')),
                ('stock', models.ForeignKey(help_text='The Stock row this movement affects.', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stock', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['stock', '-created'], name='inventory_s_stock_i_251b8b_idx'), models.Index(fields=['movement_type', '-created'], name='inventory_s_movemen_8c9534_idx'), models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('delta__gt', 0)), name='stock_movement_delta_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('variant', 'warehouse'), name='unique_stock_per_variant_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity', 0), ('reserved_quantity__lte', models.F('quantity')), _connector='OR'), name='stock_reserved_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_order_qty', 0), ('maximum_order_qty__gte', models.F('minimum_order_qty')), _connector='OR'), name='stock_max_order_qty_gte_min'),
        ),
    ]
