# Generated by Django 6.1 on 2026-08-23 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Set for SALE, RESERVE, and RELEASE movements.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.orderitem', verbose_name='Order Item'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='Staff user who triggered this movement. Null = automated/system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='staff.staffprofile', verbose_name='Performed By'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock',
            field=models.ForeignKey(help_text='The Stock row this movement affects.', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stock', verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='contact_person',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for this warehouse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to='staff.staffprofile', verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock', '-created'], name='inventory_s_stock_i_251b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created'], name='inventory_s_movemen_8c9534_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('delta__gt', 0)), name='stock_movement_delta_positive'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('variant', 'warehouse'), name='unique_stock_per_variant_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='stock_reserved_lte_quantity'),
        ),
    ]
