# Generated by Django 6.1 on 2026-08-26 05:08

import apps.catalogue.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Unique internal key. Use lowercase with underscores, e.g. 'colour', 'storage_capacity', 'material'.", max_length=100, unique=True, validators=[apps.catalogue.validators.validate_attribute_name], verbose_name='Attribute Name')),
                ('label', models.CharField(help_text="Customer-facing label shown in the storefront and admin, e.g. 'Colour', 'Storage Capacity (GB)', 'Material'.", max_length=100, verbose_name='Display Label')),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long Text'), ('integer', 'Integer'), ('big_integer', 'Big Integer'), ('decimal', 'Decimal'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('json', 'JSON'), ('uuid', 'UUID'), ('email', 'Email'), ('url', 'URL'), ('color', 'Colour'), ('single_select', 'Single Select'), ('multi_select', 'Multi Select')], default='text', help_text='Determines the widget, validation, and coercion applied to values. SINGLE_SELECT / MULTI_SELECT require AttributeOption rows.', max_length=20, verbose_name='Value Type')),
                ('unit_dimension', models.CharField(choices=[('none', 'None / Dimensionless'), ('mass', 'Mass (weight)'), ('length', 'Length'), ('area', 'Area'), ('volume', 'Volume'), ('temperature', 'Temperature'), ('power', 'Power'), ('energy', 'Energy'), ('voltage', 'Voltage'), ('current', 'Electric Current'), ('frequency', 'Frequency'), ('speed', 'Speed'), ('pressure', 'Pressure'), ('storage', 'Digital Storage'), ('time_unit', 'Time'), ('luminous_flux', 'Luminous Flux (brightness)'), ('angle', 'Angle'), ('concentration', 'Concentration / Density'), ('quantity', 'Quantity / Count')], db_index=True, default='none', help_text="Measurement category for this attribute. Selecting a dimension filters the Unit Symbol choices to only those that belong to that category. Leave as 'None / Dimensionless' for text, colour, or select attributes.", max_length=20, verbose_name='Unit Dimension')),
                ('unit_symbol', models.CharField(blank=True, default='', help_text="Pint-recognised unit symbol displayed after numeric values, e.g. 'kilogram' -> 'kg', 'centimeter' -> 'cm'. Must belong to the selected Unit Dimension. Leave blank for attributes that have no unit.", max_length=30, validators=[apps.catalogue.validators.validate_unit_symbol], verbose_name='Unit Symbol')),
            ],
            options={
                'verbose_name': 'Attribute Definition',
                'verbose_name_plural': 'Attribute Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Show this item in featured/promotional sections on the storefront.', verbose_name='Featured')),
                ('product_type', models.CharField(choices=[('physical', 'Physical Product'), ('digital', 'Digital Download'), ('subscription', 'Subscription'), ('service', 'Service'), ('membership', 'Membership'), ('gift_card', 'Gift Card'), ('donation', 'Donation'), ('event', 'Event Ticket'), ('course', 'Online Course'), ('software_license', 'Software License'), ('bundle', 'Bundle'), ('pre_order', 'Pre-order'), ('rental', 'Rental')], db_index=True, default='physical', help_text='Routing key: determines which fulfilment app handles this product. Contact a developer to add new types.', max_length=20, verbose_name='Product Type')),
                ('fulfilment_type', models.CharField(choices=[('shipment', 'Shipment'), ('local_delivery', 'Local Delivery'), ('store_pickup', 'Store Pickup'), ('download', 'Download'), ('email', 'Email Delivery'), ('license_key', 'License Key'), ('streaming', 'Streaming Access'), ('account_provision', 'Account Provisioning'), ('subscription', 'Recurring Subscription'), ('service_appointment', 'Service Appointment'), ('event_access', 'Event Access'), ('manual', 'Manual Fulfilment')], db_index=True, default='shipment', help_text='Routing key: how this product is delivered to the buyer. Contact a developer to add new fulfilment methods.', max_length=25, verbose_name='Fulfilment Type')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title for search engines. Falls back to product name if empty.', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search results. Max 160 characters.', max_length=160, verbose_name='Meta Description')),
                ('other_attributes', models.JSONField(blank=True, default=dict, help_text='Arbitrary product-level attributes not covered by the structured attribute assignment system. Stored as a plain JSON object.', verbose_name='Extra Attributes')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, help_text="All types stored as strings. Integer/BigInteger: '256'. Decimal/Float: '0.350'. Boolean: 'true'/'false'. Date: 'YYYY-MM-DD'. Time: 'HH:MM:SS'. DateTime: 'YYYY-MM-DDTHH:MM:SS'. JSON: valid JSON. UUID: standard UUID string. Colour: '#RRGGBB'. SingleSelect: one option value. MultiSelect: option values joined by ','.", max_length=500, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Product Attribute Value',
                'verbose_name_plural': 'Product Attribute Values',
                'ordering': ['product', 'definition__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, upload_to='brands/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Product Brand',
                'verbose_name_plural': 'Product Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Show this item in featured/promotional sections on the storefront.', verbose_name='Featured')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Category Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, help_text='Describe the image for accessibility and SEO.', max_length=255, verbose_name='Alt Text')),
                ('is_primary', models.BooleanField(default=False, help_text='Only one image per variant should be primary.', verbose_name='Primary Image')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['product_variant', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit -- unique across the entire catalogue.', max_length=100, unique=True, validators=[apps.catalogue.validators.validate_sku], verbose_name='SKU')),
                ('other_attributes', models.JSONField(blank=True, default=dict, help_text='Arbitrary variant-level attributes not covered by the structured attribute assignment system. Stored as a plain JSON object.', verbose_name='Extra Attributes')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive variants are hidden from the storefront.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['product', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, help_text="All types stored as strings. Integer/BigInteger: '256'. Decimal/Float: '0.350'. Boolean: 'true'/'false'. Date: 'YYYY-MM-DD'. Time: 'HH:MM:SS'. DateTime: 'YYYY-MM-DDTHH:MM:SS'. JSON: valid JSON. UUID: standard UUID string. Colour: '#RRGGBB'. SingleSelect: one option value. MultiSelect: option values joined by ','.", max_length=500, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Variant Attribute Value',
                'verbose_name_plural': 'Variant Attribute Values',
                'ordering': ['variant', 'definition__name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeAssignment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=False, help_text='A value must be supplied for every target entity.', verbose_name='Required')),
                ('is_searchable', models.BooleanField(default=False, help_text='Include this attribute in full-text search indexing.', verbose_name='Searchable')),
                ('is_filterable', models.BooleanField(default=False, help_text='Expose this attribute as a faceted filter in listings.', verbose_name='Filterable')),
                ('is_comparable', models.BooleanField(default=False, help_text='Show this attribute in the product comparison table.', verbose_name='Comparable')),
                ('visible_on_listing', models.BooleanField(default=False, help_text='Show this attribute value on product listing cards.', verbose_name='Visible on Listing')),
                ('visible_on_detail', models.BooleanField(default=True, help_text='Show this attribute value on the product detail page.', verbose_name='Visible on Detail')),
                ('allow_override', models.BooleanField(default=True, help_text='When True, a product or variant can override the category default value.', verbose_name='Allow Override')),
                ('generates_variants', models.BooleanField(default=False, help_text="When True (and scope=VARIANT), the variant service uses this attribute's options to build the SKU matrix.", verbose_name='Generates Variants')),
                ('default_value', models.CharField(blank=True, help_text='Pre-filled value for new entities assigned to this target. Leave blank for no default.', max_length=500, verbose_name='Default Value')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Controls attribute ordering within a target. Lower = first.', verbose_name='Display Order')),
                ('scope', models.CharField(choices=[('product', 'Product-level'), ('variant', 'Variant-level')], default='variant', help_text='PRODUCT: same value for every variant. VARIANT: what makes variants different.', max_length=7, verbose_name='Scope')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='catalogue.attributedefinition', verbose_name='Attribute Definition')),
            ],
            options={
                'verbose_name': 'Category Assignment',
                'verbose_name_plural': 'Category Assignments',
                'ordering': ['display_order', 'definition__name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Customer-facing display name, e.g. 'Signal Red'.", max_length=100, verbose_name='Label')),
                ('value', models.CharField(help_text="Machine key stored in the attribute value field, e.g. 'signal_red'. Do not change after values have been saved against this option.", max_length=100, validators=[apps.catalogue.validators.validate_option_value], verbose_name='Value')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive options are hidden from new selections but existing attribute values that reference this option remain valid.', verbose_name='Active')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in select widgets.', verbose_name='Display Order')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Optional arbitrary data, e.g. {'hex': '#FF0000'} for colour swatches.", verbose_name='Metadata')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalogue.attributedefinition', verbose_name='Attribute Definition')),
            ],
            options={
                'verbose_name': 'Attribute Option',
                'verbose_name_plural': 'Attribute Options',
                'ordering': ['definition', 'display_order', 'label'],
            },
        ),
    ]
