# Generated by Django 6.1 on 2026-08-26 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_class',
            field=models.ForeignKey(blank=True, help_text="Source of truth for tax calculation at checkout. Resolves to TaxRate based on customer's country/state. If empty, auto-populated from category.default_tax_class on first save.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pricing.taxclass', verbose_name='Tax Class'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='catalogue.attributedefinition', verbose_name='Attribute'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalogue.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.productbrand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='default_tax_class',
            field=models.ForeignKey(blank=True, help_text='Bulk-set default for products in this category. Used at product creation time if the product has no tax_class set. Not read directly at checkout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pricing.taxclass', verbose_name='Default Tax Class'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Drives which attribute definitions apply to this product.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.productcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='attributeassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_assignments', to='catalogue.productcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalogue.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.productvariant', verbose_name='Product Variant'),
        ),
        migrations.AddField(
            model_name='variantattributevalue',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='catalogue.attributedefinition', verbose_name='Attribute'),
        ),
        migrations.AddField(
            model_name='variantattributevalue',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalogue.productvariant', verbose_name='Product Variant'),
        ),
        migrations.AddConstraint(
            model_name='attributeoption',
            constraint=models.UniqueConstraint(fields=('definition', 'value'), name='unique_attribute_option_value'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'definition'), name='unique_product_attribute_value'),
        ),
        migrations.AlterUniqueTogether(
            name='attributeassignment',
            unique_together={('category', 'definition', 'scope')},
        ),
        migrations.AddConstraint(
            model_name='variantattributevalue',
            constraint=models.UniqueConstraint(fields=('variant', 'definition'), name='unique_variant_attribute_value'),
        ),
    ]
