# Generated by Django 6.1 on 2026-08-26 05:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierAccount',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('carrier_code', models.CharField(max_length=30, unique=True, verbose_name='Carrier Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('credentials', models.JSONField(default=dict, help_text="API keys, endpoint URLs, and carrier-specific config. Values are encrypted at rest via the field's storage backend.", verbose_name='Credentials')),
            ],
            options={
                'verbose_name': 'Carrier Account',
                'verbose_name_plural': 'Carrier Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('estimated_days_min', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Estimated Days (Min)')),
                ('estimated_days_max', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Estimated Days (Max)')),
                ('base_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Base Rate')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_methods', to='shipping.carrieraccount', verbose_name='Carrier Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_methods', to='pricing.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Tracking Number')),
                ('label_url', models.URLField(blank=True, max_length=500, verbose_name='Label URL')),
                ('label_data', models.BinaryField(blank=True, verbose_name='Label Data')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('label_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Label Generated At')),
                ('carrier_reference', models.CharField(blank=True, max_length=100, verbose_name='Carrier Reference')),
                ('label_error', models.TextField(blank=True, help_text='Set when label generation fails. Cleared on successful retry.', verbose_name='Label Error')),
                ('fulfilment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='delivery.fulfilment', verbose_name='Fulfilment')),
                ('shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.shippingmethod', verbose_name='Shipping Method')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_code', models.CharField(max_length=30, verbose_name='Event Code')),
                ('event_timestamp', models.DateTimeField(verbose_name='Event Timestamp')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('raw_payload', models.JSONField(default=dict, verbose_name='Raw Payload')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shipping.shipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'Tracking Event',
                'verbose_name_plural': 'Tracking Events',
                'ordering': ['event_timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='shippingmethod',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_days_min__isnull', True), ('estimated_days_max__isnull', True), ('estimated_days_min__lte', models.F('estimated_days_max')), _connector='OR'), name='shipping_method_days_min_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='shippingmethod',
            constraint=models.CheckConstraint(condition=models.Q(('base_rate__gte', 0)), name='shipping_method_base_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('tracking_number', ''), _negated=True), fields=('tracking_number',), name='unique_shipment_tracking_number'),
        ),
        migrations.AddConstraint(
            model_name='trackingevent',
            constraint=models.UniqueConstraint(fields=('shipment', 'event_code', 'event_timestamp'), name='unique_tracking_event_per_shipment'),
        ),
    ]
