# Generated by Django 6.1 on 2026-08-23 05:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='Star rating from 1 (lowest) to 5 (highest).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('title', models.CharField(blank=True, help_text="Optional short headline, e.g. 'Great product!'", max_length=150, verbose_name='Review Title')),
                ('body', models.TextField(blank=True, help_text='Detailed review text.', verbose_name='Review Body')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Set automatically by the review service when the customer has a delivered order containing this product. Prefer linking order_item for accurate verification.', verbose_name='Verified Purchase')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Controls storefront visibility. When GlobalSettings.auto_publish_reviews is True this is set automatically on submission. Otherwise staff set this manually to make the review visible.', verbose_name='Published')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='customers.customerprofile', verbose_name='Customer')),
                ('order_item', models.ForeignKey(blank=True, help_text='The specific order line this review is tied to. Used by the service to set is_verified_purchase automatically. Leave blank only for legacy / migrated reviews.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.orderitem', verbose_name='Order Item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalogue.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'product'), name='unique_review_per_customer_product'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5')],
            },
        ),
    ]
