name: Security

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version-file: ".python-version"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Detect Secrets
        run: uv run detect-secrets-hook --baseline .secrets.baseline

      - name: Dependency Audit
        run: uv run pip-audit
